from __future__ import annotations

import json
import os

import httpx

from app.models.schemas import AIDecision, AlertPayload, AnalyzeResponse


class LLMBridgeAgent:
    """Bridge agent for Qwen-compatible chat completion with safe fallback."""

    def __init__(self) -> None:
        self.api_key = os.getenv("QWEN_API_KEY", "").strip()
        self.base_url = os.getenv("QWEN_BASE_URL", "https://dashscope.aliyuncs.com/compatible-mode/v1").rstrip("/")
        self.model = os.getenv("QWEN_MODEL", "qwen-plus")
        self.timeout_seconds = float(os.getenv("LLM_TIMEOUT_SECONDS", "8"))

    def enhance(self, payload: AlertPayload, rule_result: AnalyzeResponse) -> AIDecision:
        if not self.api_key:
            return self._mock_decision(rule_result)

        try:
            return self._call_qwen(payload=payload, rule_result=rule_result)
        except Exception:
            return self._mock_decision(rule_result)

    def _call_qwen(self, payload: AlertPayload, rule_result: AnalyzeResponse) -> AIDecision:
        prompt = {
            "task": "Assess security alert and return strict JSON decision.",
            "required_json_schema": {
                "summary": "string",
                "confidence": "number(0~1)",
                "suggested_action": "monitor|manual_review|block_and_isolate",
                "reasoning": "string",
            },
            "alert": payload.model_dump(),
            "rule_result": {
                "risk_score": rule_result.risk_score,
                "recommendation": rule_result.recommendation,
            },
        }

        with httpx.Client(timeout=self.timeout_seconds) as client:
            response = client.post(
                f"{self.base_url}/chat/completions",
                headers={
                    "Authorization": f"Bearer {self.api_key}",
                    "Content-Type": "application/json",
                },
                json={
                    "model": self.model,
                    "messages": [
                        {
                            "role": "system",
                            "content": "You are a SOC assistant. Return JSON only.",
                        },
                        {"role": "user", "content": json.dumps(prompt, ensure_ascii=False)},
                    ],
                    "temperature": 0.1,
                },
            )
            response.raise_for_status()
            body = response.json()

        content = body["choices"][0]["message"]["content"]
        parsed = self._extract_json(content)
        return AIDecision(
            summary=str(parsed.get("summary", "LLM decision available."))[:500],
            confidence=float(parsed.get("confidence", 0.6)),
            suggested_action=parsed.get("suggested_action", rule_result.recommendation),
            reasoning=str(parsed.get("reasoning", "Generated by Qwen."))[:1000],
        )

    def _extract_json(self, content: str) -> dict[str, object]:
        try:
            return json.loads(content)
        except json.JSONDecodeError:
            start = content.find("{")
            end = content.rfind("}")
            if start >= 0 and end > start:
                return json.loads(content[start : end + 1])
            raise

    def _mock_decision(self, rule_result: AnalyzeResponse) -> AIDecision:
        if rule_result.risk_score >= 85:
            return AIDecision(
                summary="High confidence high-risk alert, isolate first and verify quickly.",
                confidence=0.88,
                suggested_action="block_and_isolate",
                reasoning="Rule score is high and multiple high-risk indicators are present.",
            )
        if rule_result.risk_score >= 60:
            return AIDecision(
                summary="Medium-high risk event, escalate for analyst review.",
                confidence=0.74,
                suggested_action="manual_review",
                reasoning="Risk level indicates potential threat but requires human validation.",
            )
        return AIDecision(
            summary="Low-risk signal, continue monitoring.",
            confidence=0.69,
            suggested_action="monitor",
            reasoning="No strong malicious indicators from current rules.",
        )